### ISSUE TITLE
Seasonal Events / Grand Company categories being mixed up

### ISSUE THREAD

**Issue by bensonkhau** [JamesDonnelly/xiv-achievements#1]
http://jamesmdonnelly.com/xiv-achievements/#/2822851/5891145
It looks like your Seasonal Events are being categorized under the wrong category; for the left person, they don't exist; for the right person, it goes under the wrong category (should be under Quests)
<img width="1261" alt="screen shot 2017-02-14 at 11 54 32 am" src="https://cloud.githubusercontent.com/assets/5842622/22946535/8848ae3a-f2ac-11e6-898f-bd1e76d267f3.png">

**Comment by JamesDonnelly** [comment]
Thanks for the report!
